config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'blogs#index'
  resources :blogs do 
    resources :comments, :except => [:index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    has_many :comments, dependent: :destroy
    validates_associated :comments
    validates :title, presence: true, length: {maximum: 60}
    validates :location, presence: true
    validates :content, presence: true, length: {minimum: 50}



  def country_name
    # country = ISO3166::Country[country]
    # country.translations[I18n.locale.to_s] || country.name
    country = self.country
    ISO3166::Country[country]
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :blog
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  http_basic_authenticate_with name: "admin", password: "secretpassword", 
  except: [:index, :show, :new, :create]

  def index
    @blogs = Blog.order("created_at DESC")
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def new
    @new_blog = Blog.new()
  end

  def create
    @new_blog = Blog.new(blog_params)

    if @new_blog.save
      redirect_to(root_path)
    else
      render 'new'
    end
  end

  def edit
    @edit_blog = Blog.find(params[:id])
  end

  def update
    @edit_blog = Blog.find(params[:id])

    if @edit_blog.update(blog_params)
      redirect_to(blog_path(@edit_blog))
    else
      render 'edit'
    end
  end

  def destroy
    @delete_blog = Blog.find(params[:id])
    @delete_blog.destroy
    redirect_to root_path
  end

  private
    def blog_params
      params.require(:blog).permit(:title, :location, :country, :budget, :activity, :content, :author, :img_url)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with name: "admin", password: "secretpassword",
  only: [:destroy]

  def create
    @blog = Blog.find(params[:blog_id])

    #adds the newly created comment into the blog.comments array
    @comment = @blog.comments.create(comment_params)

    redirect_to blog_path(@blog)
  end

  def destroy
    @blog = Blog.find(params[:blog_id])
    @delete_comment = @blog.comments.find(params[:id])
    @delete_comment.destroy
    redirect_to blog_path(@blog)
  end

  private
    def comment_params
      params.require(:comment).permit(:name, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<div class="form-group">
  <%=f.label :title, "Title of the Blog Post" %>
  <%=f.text_field :title, size: '60', class: 'form-control'%>
  <br>
</div>

<div class="form-row">
  <div class="form-group col-md-6">
    <%=f.label :location %>
    <%=f.text_field :location, size: '30', class: 'form-control'%>
    <br>
  </div>

  <%#TODO - Select tag with all countries listed%>
  <div class="form-group col-md-6">
    <%=f.label :country %>
    <%#f.text_field :country, class: 'form-control'%>
    <%= f.country_select :country, {priority_countries: ["AU"]}, {class: 'form-control'}%>
    <br>
  </div>
</div>

<div class="form-row">
  <div class="form-group col-md-6">
    <%#TODO - Currency and algorithm to convert to AUD%>
    <%=f.label :budget, "Budget (in AUD)" %>
    <%=f.number_field :budget, class: 'form-control'%>
    <br>
  </div>

  <%#TODO - Select tag with common activities and 'Other'
  with pops out a text_field%>
  <div class="form-group col-md-6">
    <%=f.label :activity %>
    <%=f.text_field :activity, class: 'form-control'%>
    <br>
  </div>
</div>

<div class="form-group">
  <%=f.label :img_url, "Image URL" %>
  <%=f.text_field :img_url, size: '60', class: 'form-control'%>
  <br>
</div>

<div class="form-group">
  <%=f.label :author, "Author" %>
  <%=f.text_field :author, size: '50', class: 'form-control'%>
  <br>
</div>

  <%=f.label :content %>
  <%=f.text_area :content, size: "60x12", class: 'form-control'%>
  <br>

app/views/blogs/edit.html.erb
<div class="container-fluid">

<div class="row justify-content-center">

<%= form_with(model: @edit_blog, local: true, html: {class: 'col-4 p-3 mb-2 bg-light text-dark'}) do |f|%>
<button type="button" class="btn btn-outline-primary"><%=link_to("Back to Blog Page", blog_path(@edit_blog)) %></button>

<h1>Edit Post</h1>
<% if @edit_blog.errors.any? %>
  <div id="error_explanation"> 
    <ul>
    <% @edit_blog.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


  <%= render 'form', f: f %>

  <%=f.submit "Update Post", class: "btn btn-warning"%>


<%end%>

app/views/blogs/index.html.erb
<main>
  <div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
      <div class="col-md-5 p-lg-5 mx-auto my-5">
        <h1 class="display-4 font-weight-normal">Travel Blog</h1>
        <p class="lead font-weight-normal">Your one stop blogsite for your travel plans.</p>
        <%= link_to 'Add New Blog Post', new_blog_path, class: "btn btn-outline-success" %>

      </div>
  </div>

  
  <div class="container">

    <%@blogs.each_slice(2) do |blogs| %>
        <div class="row mb-4">
          <div class="col-lg-6">
            <div class="mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden" style="background-image: url(<%=blogs[0].img_url%>)">
              <div class="my-3 py-3">
                <h2 class="display-5 i-h5 w-100 py-3"><%= link_to blogs[0].title, blog_path(blogs[0])%></h2>
              </div>
              <div class="bg-light text-dark box-shadow mx-auto i-div pb-3" style="width: 60%; height: 300px; border-radius: 21px 21px 0 0;">
                <p><%=blogs[0].location%></p>
                <p><%=blogs[0].country_name%></p>
                <p>Budget: <%=blogs[0].budget%></p>
                <p>Activity: <%=blogs[0].activity%></p>
                <p>Author: <%=blogs[0].author%></p>
                <%= link_to 'Read More', blog_path(blogs[0]), class: "btn btn-outline-primary w-75 h-auto m-auto" %>
              </div>
            </div>
          </div>

          <%if !blogs[1].nil?%>
            <div class="col-lg-6">
              <div class="mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden" style="background-image: url(<%=blogs[1].img_url%>)">
                <div class="my-3 p-3">
                  <h2 class="display-5 i-h5 py-3"><%= link_to(blogs[1].title, blog_path(blogs[1]))%></h2>
                </div>
                <div class="bg-light text-dark box-shadow mx-auto i-div pb-3" style="width: 60%; height: 300px; border-radius: 21px 21px 0 0;">
                  <p ><%=blogs[1].location%></p>
                  <p ><%=blogs[1].country_name%></p>
                  <p >Budget: <%=blogs[1].budget%></p>
                  <p >Activity: <%=blogs[1].activity%></p>
                <p>Author: <%=blogs[1].author%></p>
                <%= link_to 'Read More', blog_path(blogs[1]), class: "btn btn-outline-primary w-75 h-auto m-auto" %>
                </div>
              </div>
            </div>
          <%end%>

        </div>
    <%end%>

  </div>

</main>

app/views/blogs/new.html.erb
<div class="container-fluid">

<div class="row justify-content-center">
<%= form_with(model: @new_blog, local: true, html: {class: 'col-4 p-3 mb-2 bg-light text-dark'}) do |f|%>
<button type="button" class="btn btn-outline-primary"><%=link_to("Back to Home Page", root_path) %></button>

<h1>Create New Post</h1>
<% if @new_blog.errors.any? %>
  <div id="error_explanation" class="p-3 mb-2 bg-danger text-white">
    <ul>
    <% @new_blog.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

  <%= render 'form', f: f %>

  <%=f.submit "Create New Post", class: "btn btn-success"%>


<%end%>
</div>
</div>

app/views/blogs/show.html.erb
<main class='container-fluid'>


<section class="banner" style="background-image: url(<%=@blog.img_url%>)">
<div class="overlay text-light">
<div>
<h1 class="display-2"><%= @blog.title%></h1>
<p class="display-5"><%= @blog.location%></p>
<p class="display-5"><%= @blog.country_name%></p>
<p class="display-5">Budget: $<%= @blog.budget%> AUD</p> <%#TODO%>
<p class="display-5">Activity: <%= @blog.activity%></p>
<p class="display-5">by: <%= @blog.author%></p>
<button type="button" class="btn btn-success"><a href="#content">Start Reading</a></button>
</div>
</div>
</section>

<section class="container my-4">
<div class="main bg-light">
<h2 id="content" class="display-4 text-center"><%= @blog.title%></h2>
<p class="px-4"><%= @blog.content%></p>
<p>This post was created on:
<%= @blog.created_at%>
</p>
</div>

<div class="row buttons d-flex flex-wrap justify-content-around">
<button type="button" class="w-100 col-lg-3 btn btn-outline-primary"><%=link_to("Back to Home Page", root_path) %></button>
<button type="button" class="w-100 col-lg-3 btn btn-warning"><%=link_to("Edit Blog Post", edit_blog_path(@blog)) %></button>
<button type="button" class="w-100 col-lg-3 btn btn-danger"><%= link_to 'Delete Blog Post', blog_path(@blog), method: 'delete', data: { confirm: "Are you sure you want to delete #{@blog[:title]} blog?"} %></button>
</div>
</section>

<hr>
<section class="container">
<h2>Comments</h2>


<% @blog.comments.each do |comment| %>
    <p><%= comment.name %> says:</p>
    <div class="bg-light">
    <p>"<%= comment.content %>"</p>
    <p>on <%= comment.created_at %></p>
    </div>
    <button type="button" class="btn btn-danger"><%= link_to 'Delete Comment', [comment.blog, comment], method: 'delete', data: { confirm: "Are you sure you want to delete this comment?"} %></button>

    <hr>
<%end%>

<div class="container-fluid mb-4">
<%= form_with(model: [ @blog, @blog.comments.build], local: true) do |f| %>
    <div class="form-group">
    <%=f.label :name, "Please provide your name:" %>
    <%= f.text_field :name, size: '30', class: 'mw-100'%>
    </div>
    <div class="form-group">
    <%=f.text_area :content, size: '60x6', placeholder: "Please put your comments here ...", class: 'mw-100'%>
    </div>
    <%= f.submit "Create Comment", class: 'btn btn-success' %>
<%end%>
</div>
</section>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TravelBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>